services:
  HMMH\SolrFileIndexer\Backend\Widgets\IndexableDocumentsLanguageWidget:
    arguments: ['indexableDocumentsLanguage']
    tags:
      - name: dashboard.widget
        identifier: indexableDocumentsLanguage
        widgetGroups: 'solr_file_indexer'
  HMMH\SolrFileIndexer\Backend\Widgets\IndexableDocumentsDomainWidget:
    arguments: ['indexableDocumentsDomain']
    tags:
      - name: dashboard.widget
        identifier: indexableDocumentsDomain
        widgetGroups: 'solr_file_indexer'
